apiVersion: v1                      
kind: Namespace                 
metadata:
  name: docs-mcp-server
---
kind: Service
apiVersion: v1
metadata:
  name: docs-mcp-server-worker
  namespace: docs-mcp-server
spec:
  ports:
    - name: docs-mcp-server-worker
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 0
  selector:
    name: docs-mcp-server-worker
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
---
kind: Service
apiVersion: v1
metadata:
  name: docs-mcp-server
  namespace: docs-mcp-server
spec:
  ports:
    - name: docs-mcp-server
      protocol: TCP
      port: 6280
      targetPort: 6280
      nodePort: 0
  selector:
    name: docs-mcp-server
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
---
kind: Service
apiVersion: v1
metadata:
  name: docs-mcp-server-ui
  namespace: docs-mcp-server
spec:
  ports:
    - name: docs-mcp-server-ui
      protocol: TCP
      port: 6281
      targetPort: 6281
      nodePort: 0
  selector:
    name: docs-mcp-server-ui
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: docs-mcp-server-ui
  namespace: docs-mcp-server
spec:
  to:
    kind: Service
    name: docs-mcp-server-ui
    weight: 100
  port:
    targetPort: 6281
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docs-mcp-server-worker-data
  namespace: docs-mcp-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: docs-mcp-server
  namespace: docs-mcp-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: docs-mcp-server
  template:
    metadata:
      labels:
        name: docs-mcp-server
    spec:
      containers:
        - name: docs-mcp-server
          image: nexus.clg.lab:5002/dev-spaces/docs-mcp-server:latest
          imagePullPolicy: Always
          args: ["mcp", "--host", "0.0.0.0", "--port", "6280", "--server-url", "http://docs-mcp-server-worker.docs-mcp-server.svc.cluster.local:8080/api"]
          ports:
            - containerPort: 6280
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 6280
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 6280
          #   initialDelaySeconds: 3
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 3072Mi
          terminationMessagePath: /dev/termination-log
          capabilities: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: docs-mcp-server-ui
  namespace: docs-mcp-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: docs-mcp-server-ui
  template:
    metadata:
      labels:
        name: docs-mcp-server-ui
    spec:
      containers:
        - name: docs-mcp-server-ui
          image: nexus.clg.lab:5002/dev-spaces/docs-mcp-server:latest
          imagePullPolicy: Always
          args: ["web", "--host", "0.0.0.0", "--port", "6281", "--server-url", "http://docs-mcp-server-worker.docs-mcp-server.svc.cluster.local:8080/api", "--no-logo"]
          ports:
            - containerPort: 6281
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 6280
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 6280
          #   initialDelaySeconds: 3
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 3072Mi
          terminationMessagePath: /dev/termination-log
          capabilities: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: docs-mcp-server-worker
  namespace: docs-mcp-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: docs-mcp-server-worker
  template:
    metadata:
      labels:
        name: docs-mcp-server-worker
    spec:
      containers:
        - name: docs-mcp-server-worker
          image: nexus.clg.lab:5002/dev-spaces/docs-mcp-server:latest
          imagePullPolicy: Always
          args: ["worker", "--host", "0.0.0.0", "--port", "8080", "--store-path", "/data", "--embedding-model", "openai:OpenVINO/Qwen3-Embedding-0.6B-int8-ov"]
          env:
          - name: OPENAI_API_KEY
            value: NA
          - name: OPENAI_API_BASE
            value: "http://qwen3-embedding-int8-ov-predictor.clg-inference.svc.cluster.local/v3"
          ports:
            - containerPort: 6280
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 6280
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 6280
          #   initialDelaySeconds: 3
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 3072Mi
          volumeMounts:
            - name: docs-mcp-server-worker-data
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          capabilities: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            privileged: false
      volumes:
        - name: docs-mcp-server-worker-data
          persistentVolumeClaim:
            claimName: docs-mcp-server-worker-data
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        seccompProfile:
          type: RuntimeDefault