apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen3-coder-30b-a3b-instruct
  namespace: dev-services-inference
  annotations:
    openshift.io/display-name: qwen3-coder-30b-a3b-instruct
    # security.opendatahub.io/enable-auth: "true"
    # serving.knative.openshift.io/enablePassthrough: "true"
    # sidecar.istio.io/inject: "true"
    # sidecar.istio.io/rewriteAppHTTPProbers: "true"
spec:
  predictor:
    nodeSelector:
      # ARC iGPU 155H Chipset
      # gpu.intel.com/device-id.0300-7d55.present: "true"
      # ARC 140T 255H Chipset
      gpu.intel.com/device-id.0300-7d51.present: "true"
    model:
      runtime: kserve-ovms-intel
      modelFormat:
        name: openvino_ir
      storageUri: oci://nexus.clg.lab:5002/openvino/qwen3-coder:latest
      args:
        - --config_path=/mnt/models/config_all.json
        - --log_level=DEBUG
        - --port=8001
        - --rest_port=8888
      resources:
        requests:
          cpu: "100m"
          memory: "32Gi"
          gpu.intel.com/i915: "1"
        limits:
          cpu: "8"
          memory: "64Gi"
          gpu.intel.com/i915: "1"
